/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2gI8JrIYLGZ
 */
import Link from "next/link"

export function Component() {
  return (
    <main className="flex flex-col items-center justify-center w-full min-h-screen bg-gray-100 dark:bg-gray-800">
      <header className="w-full py-6 px-4 sm:px-6 lg:px-8 bg-white dark:bg-gray-900 shadow-md">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Gallinas Ponedoras</h1>
          <nav className="flex space-x-4">
            <Link className="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-gray-100" href="#">
              Acerca de
            </Link>
            <Link className="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-gray-100" href="#">
              Productos
            </Link>
            <Link className="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-gray-100" href="#">
              Contacto
            </Link>
          </nav>
        </div>
      </header>
      <section className="w-full h-[50vh] md:h-[70vh]">
        <img
          alt="Gallina Ponedora"
          className="w-full h-full object-cover"
          height="1080"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1920/1080",
            objectFit: "cover",
          }}
          width="1920"
        />
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center">
          <h2 className="text-4xl font-bold text-white">Bienvenidos a Gallinas Ponedoras</h2>
          <p className="mt-4 text-lg text-white">Criamos las mejores gallinas ponedoras para su hogar o negocio.</p>
        </div>
      </section>
      <section className="w-full max-w-2xl mx-auto mt-12 px-4 sm:px-6 lg:px-8" id="about">
        <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Acerca de Nosotros</h2>
        <p className="mt-4 text-gray-700 dark:text-gray-300">
          Nuestras gallinas ponedoras de 16 semanas son de la más alta calidad, criadas en condiciones óptimas para
          garantizar su salud y productividad. Son capaces de producir hasta 7 huevos por semana, proporcionando un
          suministro constante de huevos frescos para su hogar o negocio.
        </p>
      </section>
      <section className="w-full max-w-2xl mx-auto mt-12 px-4 sm:px-6 lg:px-8" id="products">
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-2">
          <img
            alt="Gallina Ponedora"
            className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full"
            height="500"
            src="/placeholder.svg"
            width="500"
          />
          <img
            alt="Gallina Ponedora"
            className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full"
            height="500"
            src="/placeholder.svg"
            width="500"
          />
        </div>
        <div className="mt-8 space-y-4">
          <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Gallinas Ponedoras de 16 Semanas</h2>
          <p className="text-gray-700 dark:text-gray-300">
            Nuestras gallinas ponedoras de 16 semanas son de la más alta calidad, criadas en condiciones óptimas para
            garantizar su salud y productividad. Son capaces de producir hasta 7 huevos por semana, proporcionando un
            suministro constante de huevos frescos para su hogar o negocio.
          </p>
          <Link
            className="inline-flex items-center justify-center w-full px-4 py-2 border border-gray-200 border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 dark:border-gray-800"
            href="#"
          >
            Consultas y Compras
          </Link>
        </div>
      </section>
      <footer className="w-full py-6 px-4 sm:px-6 lg:px-8 bg-white dark:bg-gray-900 shadow-md mt-12" id="contact">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Contacto</h2>
          <Link
            className="inline-flex items-center justify-center px-4 py-2 border border-gray-200 border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 dark:border-gray-800"
            href="#"
          >
            WhatsApp
          </Link>
        </div>
      </footer>
    </main>
  )
}
